_147SupinfyWebRole/Controllers/PlaylistController.cs
using _147SupinfyWebRole.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace _147SupinfyWebRole.Controllers
{
    [Authorize]
    public class PlaylistController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var playlist = await db.Playlists.FindAsync(id);
            return View(playlist);
        }

        public ActionResult Create()
        {
            return View(new Playlist());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name")] Playlist playlistCurrent)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.FirstOrDefault(x => x.Email == User.Identity.Name);
                playlistCurrent.Owner = user;
                db.Playlists.Add(playlistCurrent);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = playlistCurrent.Id });
            }
            return View(playlistCurrent);

        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Playlist playlist = await db.Playlists.FindAsync(id);
            if (playlist == null)
            {
                return HttpNotFound();
            }
            return View(playlist);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            Playlist playlist = await db.Playlists.FindAsync(id);
            var ownerId = playlist.Owner.Id;
            db.Playlists.Remove(playlist);
            await db.SaveChangesAsync();
            return RedirectToAction("Show", "User", new { id = ownerId });
        }
    }
}

_147SupinfyWebRole/Controllers/UserController.cs
using _147SupinfyWebRole.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace _147SupinfyWebRole.Controllers
{
    public class UserController : Controller
    {
        ApplicationUserManager _userManager;

        public UserController()
        {

        }

        public UserController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        // GET: User
        public async Task<ActionResult> Show(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            return View(user);
        }

        [Authorize]
        public async Task<ActionResult> Follow(string id)
        {
            string username = User.Identity.Name;
            ApplicationUser user = await UserManager.FindByNameAsync(username);
            var userToFollow = await UserManager.FindByIdAsync(id);
            user.Following.Add(userToFollow);
            await UserManager.UpdateAsync(user);
            return RedirectToAction("Show", new { id = id });
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }
}

_147SupinfyWebRole/Views/User/Show.cshtml
@using _147SupinfyWebRole.Models;
@model ApplicationUser
@{
    ViewBag.Title = "UserPage";
}
<br />
<div class="row">
    <div class="col-md-3 col-sm-3 col-xs-3" style="text-align: center;">
        <div style="border: 2px solid; border-radius: 5px;">
            <i class="fa fa-user fa-5x" aria-hidden="true"></i>
        </div>
    </div>
    <div class="col-md-9 col-sm-9 col-xs-9">
        <i class="fa fa-user-circle-o fa-2x" aria-hidden="true"></i>
        <label>@Model.FirstName @Model.LastName</label>
        <span class="pull-right">Date de création : @Model.CreationDate</span>
        <br />
        <span>Rôle : @Model.Role</span>
        @using (Html.BeginForm("Follow", "User", FormMethod.Post, new { id = Model.Id }))
        {
            <button type="submit" class="btn btn-default"><i class="fa fa-plus" aria-hidden="true"></i></button>
        }
    </div>
</div>
<br />

@if (Model.Role.Equals(UserRole.Administrator))
{
    @*Admin*@
    <div class="btn-group pull-right" role="group">
        <button type="button" class="btn btn-default"><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>Edit</button>
        <button type="button" class="btn btn-default"><i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>Delete</button>
    </div>
}


<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="panel panel-default">
            <table class="table table-hover">
                <thead>
                    <tr style="background-color:grey">
                        <th>
                            Playlist
                            <div class="btn-group pull-right" role="group">
                                <a href="@Url.Action("Create", "Playlist")" class="btn btn-default"><i class="fa fa-plus" aria-hidden="true"></i></a>
                                @*<a href="" class="btn btn-default"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    <a href="@Url.Action("Delete", "Playlist")" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></a>*@
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var playlist in Model.Playlists)
                    {
                        <tr>
                            <td>
                                @playlist.Name
                                <div class="btn-group pull-right" role="group">
                                    <a href="@Url.Action("Details","Playlist", new { id = playlist.Id })" class="btn btn-default"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    <a href="@Url.Action("Delete", "Playlist", new { id = playlist.Id })" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="panel panel-default">
            <table class="table table-hover">
                <thead>
                    <tr style="background-color:grey">
                        <th>
                            Friends
                            <div class="btn-group pull-right" role="group">
                                <button type="button" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ApplicationUser following in Model.Following)
                    {
                        <tr>
                            <td>@following.FirstName @following.LastName</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>