_147SupinfyWebRole/Controllers/MusicController.cs
using _147SupinfyWebRole.Models;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace _147SupinfyWebRole.Controllers
{
    public class MusicController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Music
        public async Task<ActionResult> Index()
        {
            return View(await db.Musics.ToListAsync());
        }

        // GET: Music/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = await db.FindMusicAsync(id.Value);
            music.ViewCount ++;
            db.Entry(music).State = EntityState.Modified;
            await db.SaveChangesAsync();
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // GET: Music/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Music/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int id,[Bind(Include = "Url,Name,Artist")] Music music)
        {
            if (ModelState.IsValid)
            {
                var returnedMusic = await db.CreateMusic(music);
                var returnedPlaylist = await db.Playlists.FindAsync(id);
                returnedPlaylist.Musics.Add(returnedMusic);

                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Playlist", new { id = returnedPlaylist.Id });
            }

            return View(music);
        }

        // GET: Music/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = await db.FindMusicAsync(id.Value);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Music/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Url,Name,Artist")] Music music)
        {
            if (ModelState.IsValid)
            {
                db.Entry(music).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(music);
        }

        // GET: Music/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = await db.FindMusicAsync(id.Value);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Music/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            Music music = await db.FindMusicAsync(id.Value);
            db.DeleteMusic(music);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

_147SupinfyWebRole/Controllers/PlaylistController.cs
using _147SupinfyWebRole.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace _147SupinfyWebRole.Controllers
{
    [Authorize]
    public class PlaylistController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var playlist = await db.Playlists.FindAsync(id);
            return View(playlist);
        }

        public ActionResult Create()
        {
            return View(new Playlist());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name")] Playlist playlistCurrent)
        {
            if (ModelState.IsValid)
            {
                var user = db.Users.FirstOrDefault(x => x.Email == User.Identity.Name);
                playlistCurrent.Owner = user;
                db.Playlists.Add(playlistCurrent);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { id = playlistCurrent.Id });
            }
            return View(playlistCurrent);

        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Playlist playlist = await db.Playlists.FindAsync(id);
            if (playlist == null)
            {
                return HttpNotFound();
            }
            return View(playlist);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            Playlist playlist = await db.Playlists.FindAsync(id);
            var ownerId = playlist.Owner.Id;
            db.Playlists.Remove(playlist);
            await db.SaveChangesAsync();
            return RedirectToAction("Show", "User", new { id = ownerId });
        }
    }
}

_147SupinfyWebRole/Controllers/UserController.cs
using _147SupinfyWebRole.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace _147SupinfyWebRole.Controllers
{
    public class UserController : Controller
    {
        ApplicationUserManager _userManager;

        public UserController()
        {

        }

        public UserController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        // GET: User
        public async Task<ActionResult> Show(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            return View(user);
        }

        [Authorize]
        public async Task<ActionResult> Follow(string id)
        {
            string username = User.Identity.Name;
            ApplicationUser user = await UserManager.FindByNameAsync(username);
            var userToFollow = await UserManager.FindByIdAsync(id);
            user.Following.Add(userToFollow);
            await UserManager.UpdateAsync(user);
            return RedirectToAction("Show", new { id = id });
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }
}

_147SupinfyWebRole/Views/Playlist/Create.cshtml
@using _147SupinfyWebRole.Models
@model _147SupinfyWebRole.Models.Playlist
@{
    ViewBag.Title = "Create";
}

<h2>Add a name to your playlist</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

_147SupinfyWebRole/Views/Playlist/Delete.cshtml
@using _147SupinfyWebRole.Models
@model _147SupinfyWebRole.Models.Playlist
@{
    ViewBag.Title = "Delete";
}

<h2>Delete Playlist</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Musics)
        {
            <tr>
                <td>
                    @foreach (var music in Model.Musics)
                    {
                        <iframe width="100%" height="150" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=@music.Url"> </iframe>
                    }
                </td>
            </tr>
        }

    </table>
    <input type="submit" value="Delete" class="btn btn-default" />
}

_147SupinfyWebRole/Views/Playlist/Details.cshtml
@using _147SupinfyWebRole.Models
@model _147SupinfyWebRole.Models.Playlist
@{
    ViewBag.Title = "Details";
}

<h2>Playlist</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
            <div class="pull-right">
                <a href="@Url.Action("Create", "Music", new { id = Model.Id })" class="btn btn-default"><i class="fa fa-plus" aria-hidden="true"></i> Add music</a>
            </div>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Musics)
    {
        <tr>
            <td>
                @foreach (var music in Model.Musics)
                {
                    <iframe width="100%" height="150" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=@music.Url"> </iframe>
                }
            </td>
        </tr>
    }
    
</table>

<a href="@Url.Action("Show","User", new { id = Model.Owner.Id })">Back to profile</a>